### ISSUE TITLE
Save courses after search

### ISSUE THREAD

**Issue by Hunter-Buckhorn** [UCSB-CS56-Projects/cs56-utilities-GEAR-scraper#10]
Add the ability to prompt the user whether or not to save a course after it has been searched, save the courses to a list and add the ability to reset the list with a button

200 points

**Comment by arda-** [comment]
approved, 150 points

**Comment by Hunter-Buckhorn** [comment]
aww

**Comment by Hunter-Buckhorn** [comment]
Closed
