### ISSUE TITLE
Lab05 code review

### ISSUE THREAD

**Issue by Hunter-Buckhorn** [UCSB-CS56-Projects/cs56-utilities-GEAR-scraper#11]
Do the lab05 code review for the legacy code project
(discussed in lecture on Monday, February 22nd)

200 points

**Comment by arda-** [comment]
Completing Lab05's code review of the project does not directly count as points toward the legacy code project; however, if any changes are made to the code that resolve issues in the course of Lab05, they do count toward the 1000 required points of lab07.

See the end of [Lab05's instructions](https://foo.cs.ucsb.edu/56wiki/index.php/W16:Labs:lab05) for Professor Conrad's explanation of this.
