### ISSUE TITLE
Update GEAR source

### ISSUE THREAD

**Issue by EasterAndJay** [UCSB-CS56-Projects/cs56-utilities-GEAR-scraper#4]
Update URL and page numbers to parse classes from.

Approved 50 points

**Comment by Hunter-Buckhorn** [comment]
Closed

**Comment by EasterAndJay** [comment]
@Hunter-Buckhorn Please submit a pull request with the issue number(#4)

**Comment by Hunter-Buckhorn** [comment]
Just submitted, I had to fix some compile errors

Hunter Buckhorn
