### ISSUE TITLE
Add search function

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-utilities-GEAR-scraper#7]
Implement a search bar that the user can type into to find courses, and retrieve information about them.

250 points.

**Comment by Hunter-Buckhorn** [comment]
Add the ability to filter the scope of the user's search by clicking the checkboxes
100 points

**Comment by arda-** [comment]
Approved, integrated into the main issue comment. Further points possible, pending evaluation!

**Comment by Hunter-Buckhorn** [comment]
Closed
