### ISSUE TITLE
improve README

### ISSUE THREAD

**Issue by arda-** [UCSB-CS56-Projects/cs56-utilities-GEAR-scraper#8]
README could be more comprehensive, with information such as:

- running the game
- (at least) a high level description of how the program works
- a description of the various files/directories
- project history
- screenshots

75 points

**Comment by Hunter-Buckhorn** [comment]
Add write up about how PDFs are encoded, their layout, and how the Apache PDFBox API parsers the pdf and pulls data into the data scraper

75 points

**Comment by arda-** [comment]
Approved, total 175 points between both parts of improving the Readme.
